spring.application.name=tunahan
spring.datasource.url=jdbc:postgresql://localhost:5432/Banka
spring.datasource.username=postgres
spring.datasource.password=1968Tuna
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
jwt.secret=cokGizliBirAnahtarEnAz32KarakterOlmalidir1234
jwt.expiration=86400000